FROM python:3.9

ENV KEYS_DIR "keys"
ENV ROOT_DIR "sso-user-service"
WORKDIR /${ROOT_DIR}

ARG SECRET_KEY=${SECRET_KEY}
ARG ENVIRONMENT=${ENVIRONMENT:-PRODUCTION}
ARG BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-*}
ARG ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-600}
ARG LONG_ACCESS_TOKEN_EXPIRE_MINUTES=${LONG_ACCESS_TOKEN_EXPIRE_MINUTES:-1440}

ARG POSTGRES_SERVER=${POSTGRES_SERVER}
ARG POSTGRES_USER=${POSTGRES_USER}
ARG POSTGRES_DB=${POSTGRES_DB}
ARG POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ARG AUTORUN_MIGRATIONS=${AUTORUN_MIGRATIONS:-True}

ARG TEST_POSTGRES_SERVER=${TEST_POSTGRES_SERVER:-localhost}
ARG TEST_POSTGRES_USER=${TEST_POSTGRES_USER:-postgres}
ARG TEST_POSTGRES_DB=${TEST_POSTGRES_DB:-postgres}
ARG TEST_POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD:-postgres}

ARG FIRST_SUPERUSER_USERNAME=${FIRST_SUPERUSER_USERNAME:-admin}
ARG FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD:-admin}

ARG SSO_APP_SECRET=${SSO_APP_SECRET:-b5FfcesXgwC5MWdadavb1Yg4ivMfoYX}
ARG PRIVATE_KEY=${PRIVATE_KEY:-private.pem}
ARG PUBLIC_KEY=${PUBLIC_KEY:-public.pem}

ARG EMAIL_HOST_URL=${EMAIL_HOST_URL}
ARG EMAIL_CONFIRM_HOST_FORMAT=${EMAIL_CONFIRM_HOST_FORMAT}
ARG SMTP_EMAIL=${SMTP_EMAIL}
ARG SMTP_PORT=${SMTP_PORT:-465}
ARG SMTP_PASSWORD=${SMTP_PASSWORD}

ARG SOCIAL_GOOGLE_CLIENT_SECRET=${SOCIAL_GOOGLE_CLIENT_SECRET}
ARG SOCIAL_GOOGLE_CLIENT_ID=${SOCIAL_GOOGLE_CLIENT_ID}

ARG SOCIAL_MICROSOFT_CLIENT_ID=${SOCIAL_MICROSOFT_CLIENT_ID}
ARG SOCIAL_MICROSOFT_CLIENT_SECRET=${SOCIAL_MICROSOFT_CLIENT_SECRET}

RUN touch /${ROOT_DIR}/.env
RUN rm /${ROOT_DIR}/.env

RUN echo "KEYS_DIR=$KEYS_DIR" >> /${ROOT_DIR}/.env
RUN echo "SECRET_KEY=$SECRET_KEY" >> /${ROOT_DIR}/.env
RUN echo "ENVIRONMENT=$ENVIRONMENT" >> /${ROOT_DIR}/.env
RUN echo "BACKEND_CORS_ORIGINS=$BACKEND_CORS_ORIGINS" >> /${ROOT_DIR}/.env
RUN echo "ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES" >> /${ROOT_DIR}/.env
RUN echo "LONG_ACCESS_TOKEN_EXPIRE_MINUTES=$LONG_ACCESS_TOKEN_EXPIRE_MINUTES" >> /${ROOT_DIR}/.env

RUN echo "POSTGRES_SERVER=$POSTGRES_SERVER" >> /${ROOT_DIR}/.env
RUN echo "POSTGRES_USER=$POSTGRES_USER" >> /${ROOT_DIR}/.env
RUN echo "POSTGRES_DB=$POSTGRES_DB" >> /${ROOT_DIR}/.env
RUN echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> /${ROOT_DIR}/.env
RUN echo "AUTORUN_MIGRATIONS=$AUTORUN_MIGRATIONS" >> /${ROOT_DIR}/.env

RUN echo "TEST_POSTGRES_SERVER=$TEST_POSTGRES_SERVER" >> /${ROOT_DIR}/.env
RUN echo "TEST_POSTGRES_USER=$TEST_POSTGRES_USER" >> /${ROOT_DIR}/.env
RUN echo "TEST_POSTGRES_DB=$TEST_POSTGRES_DB" >> /${ROOT_DIR}/.env
RUN echo "TEST_POSTGRES_PASSWORD=$TEST_POSTGRES_PASSWORD" >> /${ROOT_DIR}/.env

RUN echo "FIRST_SUPERUSER_USERNAME=$FIRST_SUPERUSER_USERNAME" >> /${ROOT_DIR}/.env
RUN echo "FIRST_SUPERUSER_PASSWORD=$FIRST_SUPERUSER_PASSWORD" >> /${ROOT_DIR}/.env

RUN echo "SSO_APP_SECRET=$SSO_APP_SECRET" >> /${ROOT_DIR}/.env
RUN echo "PRIVATE_KEY=$PRIVATE_KEY" >> /${ROOT_DIR}/.env
RUN echo "PUBLIC_KEY=$PUBLIC_KEY" >> /${ROOT_DIR}/.env

RUN echo "EMAIL_HOST_URL=$EMAIL_HOST_URL" >> /${ROOT_DIR}/.env
RUN echo "EMAIL_CONFIRM_HOST_FORMAT=EMAIL_CONFIRM_HOST_FORMAT" >> /${ROOT_DIR}/.env
RUN echo "SMTP_EMAIL=$SMTP_EMAIL" >> /${ROOT_DIR}/.env
RUN echo "SMTP_PORT=$SMTP_PORT" >> /${ROOT_DIR}/.env
RUN echo "SMTP_PASSWORD=$SMTP_PASSWORD" >> /${ROOT_DIR}/.env

RUN echo "SOCIAL_GOOGLE_CLIENT_SECRET=$SOCIAL_GOOGLE_CLIENT_SECRET" >> /${ROOT_DIR}/.env
RUN echo "SOCIAL_GOOGLE_CLIENT_ID=$SOCIAL_GOOGLE_CLIENT_ID" >> /${ROOT_DIR}/.env

RUN echo "SOCIAL_MICROSOFT_CLIENT_ID=$SOCIAL_MICROSOFT_CLIENT_ID" >> /${ROOT_DIR}/.env
RUN echo "SOCIAL_MICROSOFT_CLIENT_SECRET=$SOCIAL_MICROSOFT_CLIENT_SECRET" >> /${ROOT_DIR}/.env

COPY ./requirements.txt /${ROOT_DIR}/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /${ROOT_DIR}/requirements.txt 

COPY . /${ROOT_DIR}
RUN mkdir ${KEYS_DIR}
RUN openssl genrsa -out ${KEYS_DIR}/private.pem 2048
RUN openssl rsa -in ${KEYS_DIR}/private.pem -outform PEM -pubout -out ${KEYS_DIR}/public.pem

EXPOSE 8080
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
# CMD ["sleep","3600"]
